org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod
mod_id=legendary_armory
mod_name=Cobblemon: Legendary Armory
mod_version=1.0.0
mod_group=com.legendaryarmory
mod_authors=arsnyde
mod_license=MIT
mod_description=Legendary Pokemon armor sets forged from Minecraft, Cobblemon and Mega Showdown materials.

# Platform
minecraft_version=1.21.1
neoforge_version=21.1.214
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Cobblemon / addons
cobblemon_version=1.8.1+1.21.1
kotlin_version=2.0.21
kff_version=5.7.0
